//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eruru.FluentAvaloniaTemplate.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eruru.FluentAvaloniaTemplate.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        internal static string AccentColor_Dark {
            get {
                return ResourceManager.GetString("AccentColor_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        internal static string AccentColor_Light {
            get {
                return ResourceManager.GetString("AccentColor_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 App Accent Color 的本地化字符串。
        /// </summary>
        internal static string AppAccentColor {
            get {
                return ResourceManager.GetString("AppAccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 App Flow Direction 的本地化字符串。
        /// </summary>
        internal static string AppFlowDirection {
            get {
                return ResourceManager.GetString("AppFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 App Font 的本地化字符串。
        /// </summary>
        internal static string AppFont {
            get {
                return ResourceManager.GetString("AppFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 App Language 的本地化字符串。
        /// </summary>
        internal static string AppLanguage {
            get {
                return ResourceManager.GetString("AppLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FluentAvalonia Template 的本地化字符串。
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 App Theme 的本地化字符串。
        /// </summary>
        internal static string AppTheme {
            get {
                return ResourceManager.GetString("AppTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change the current app flow direction 的本地化字符串。
        /// </summary>
        internal static string ChangeCurrentAppFlowDirection {
            get {
                return ResourceManager.GetString("ChangeCurrentAppFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change the current app font 的本地化字符串。
        /// </summary>
        internal static string ChangeCurrentAppFont {
            get {
                return ResourceManager.GetString("ChangeCurrentAppFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change the current app language 的本地化字符串。
        /// </summary>
        internal static string ChangeCurrentAppLanguage {
            get {
                return ResourceManager.GetString("ChangeCurrentAppLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change the current app theme 的本地化字符串。
        /// </summary>
        internal static string ChangeCurrentAppTheme {
            get {
                return ResourceManager.GetString("ChangeCurrentAppTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom Color 的本地化字符串。
        /// </summary>
        internal static string CustomColor {
            get {
                return ResourceManager.GetString("CustomColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home Page 的本地化字符串。
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left To Right 的本地化字符串。
        /// </summary>
        internal static string LeftToRight {
            get {
                return ResourceManager.GetString("LeftToRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimize to tray icon 的本地化字符串。
        /// </summary>
        internal static string MinimizeToTrayIcon {
            get {
                return ResourceManager.GetString("MinimizeToTrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ok 的本地化字符串。
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pre-set Colors 的本地化字符串。
        /// </summary>
        internal static string PresetColors {
            get {
                return ResourceManager.GetString("PresetColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preview 的本地化字符串。
        /// </summary>
        internal static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quit 的本地化字符串。
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right To Left 的本地化字符串。
        /// </summary>
        internal static string RightToLeft {
            get {
                return ResourceManager.GetString("RightToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set a custom accent color for the app 的本地化字符串。
        /// </summary>
        internal static string SetAppCustomAccentColorForApp {
            get {
                return ResourceManager.GetString("SetAppCustomAccentColorForApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show 的本地化字符串。
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System 的本地化字符串。
        /// </summary>
        internal static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SystemAccentColor 的本地化字符串。
        /// </summary>
        internal static string SystemAccentColor {
            get {
                return ResourceManager.GetString("SystemAccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use custom accent color? 的本地化字符串。
        /// </summary>
        internal static string UseCustomAccentColor {
            get {
                return ResourceManager.GetString("UseCustomAccentColor", resourceCulture);
            }
        }
    }
}
